### ISSUE TITLE
Where do I retrive the BitmapPath for a HaloCE map?

### ISSUE THREAD

**Issue by ghost** [Wunkolo/vkblam#2]
```
./vkblam ~/Downloads/HaloCEPC/HALO_install/MAPS/carousel.map <BitmapPath>
```

**Comment by Wunkolo** [comment]
The `bitmaps.map` files are within the same directory as the other maps in your installation.

In this case, it _should_ be at `~/Downloads/HaloCEPC/HALO_install/MAPS/bitmaps.map`. So the full command would be:
```
./vkblam ~/Downloads/HaloCEPC/HALO_install/MAPS/carousel.map ~/Downloads/HaloCEPC/HALO_install/MAPS/bitmaps.map
```

Note that I've only been testing this code on the retail version of Halo PC at the moment. No idea how it might handle the Halo CE caveats.

**Comment by ghost** [comment]
Works perfectly thank you!
